load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "hello-time",
    srcs = ["hello-time.go"],
    importpath = "example.com/myproject/stage3/lib",
    visibility = ["//main:__pkg__"],
)