java_library(
    name = "amir",
    srcs = ["Amir.java"],
    tags = ["pizza"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "jenny",
    srcs = ["Jenny.java"],
    tags = ["macAndCheese"],
    visibility = ["//visibility:public"],
)
