load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_android",
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
)

load("@build_bazel_rules_android//android:rules.bzl", "android_sdk_repository")

android_sdk_repository(name = "androidsdk")

http_archive(
    name = "rules_android_ndk",
    sha256 = "2ab6a97748772f289331d75caaaee0593825935d1d9d982231a437fb8ab5a14d",
    strip_prefix = "rules_android_ndk-010f4f17dd13a8baaaacc28ba6c8c2c75f54c68b",
    url = "https://github.com/bazelbuild/rules_android_ndk/archive/010f4f17dd13a8baaaacc28ba6c8c2c75f54c68b.zip",
)

load("@rules_android_ndk//:rules.bzl", "android_ndk_repository")

android_ndk_repository(name = "androidndk")
