# Starlark codelab common logo components.

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files(
    srcs = ["logos.zip"],
)

bzl_library(
    name = "logocommon_bzl",
    srcs = ["logocommon.bzl"],
    visibility = ["//visibility:private"],
)
