java_library(
    name = "cheese",
    srcs = ["Cheese.java"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "dough",
    srcs = ["Dough.java"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "macaroni",
    srcs = ["Macaroni.java"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "tomato",
    srcs = ["Tomato.java"],
    visibility = ["//visibility:public"],
)
