# Starlark codelab large logo reader components.

# TODO: Load get_logo_file_via_macro from logocommon/logocommon.bzl.

# TODO: Use get_logo_file_via_macro to build the large logo fiile.

java_binary(
    name = "logo_reader_large",
    srcs = ["LogoReaderLarge.java"],
    main_class = "exercise2.logoreaderlarge.LogoReaderLarge",
    # TODO: Uncomment the following line when the TODOs above are resolved
    # resources = [":logo_large"],
)
