load(":build_defs.bzl", "string_flag")

string_flag(
    name = "flag",
    build_setting_default = "default",
)

string_flag(
    name = "wibble",
    build_setting_default = "default",
)

string_flag(
    name = "wobble",
    build_setting_default = "default",
)

string_flag(
    name = "wubble",
    build_setting_default = "default",
)
