package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib_a",
    srcs = ["lib_a.cc"],
    hdrs = ["lib_a.h"],
    includes = ["."],
    deps = ["@com_github_google_glog//:glog"],
)
