
java_binary(
  name = "GenerateFirebaseXml",
  srcs = ["java/com/google/gms/googleservices/GenerateFirebaseXml.java"],
  deps = ["@com_google_code_gson//jar"],
  visibility = ["//visibility:public"],
)
