http_archive(
    name = "rules_cc",
    sha256 = "69e05df29f0010ba248ef8dafc1f084c8fd2f5c553da634422d8167f5c4b277b",
    strip_prefix = "rules_cc-0.2.20",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.2.20/rules_cc-0.2.20.tar.gz"],
)
