load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "ProjectRunner",
    visibility = [
        "//src/main/java/com/example/cmdline:__pkg__"
    ],
    srcs = glob(["src/main/java/com/example/*.java"]),
)
