java_library(
    name = "amir",
    visibility = ["//visibility:public"],
    srcs = ["Amir.java"],
    tags = ["pizza"],
)

java_library(
    name = "jenny",
    visibility = ["//visibility:public"],
    srcs = ["Jenny.java"],
    tags = ["macAndCheese"],
)