# Starlark codelab small logo reader components.

# TODO: Add a genrule similar to that in logoreaderlarge/BUILD to build the small logo file.

java_binary(
    name = "logo_reader_small",
    srcs = ["LogoReaderSmall.java"],
    main_class = "exercise1.logoreadersmall.LogoReaderSmall",

    # TODO: Add a resource similar to that in logoreaderlarge/BUILD, and that
    # specifies the target in the new genrule above.
)
