load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

string_flag(
    name = "project_flag",
    build_setting_default = "default value",
)

string_flag(
    name = "some_unrelated_flag",
    build_setting_default = "default value",
)
