load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Use a fork version of glog with http_archive.
http_archive(
    name = "com_github_google_glog",
    sha256 = "43e83154e0e5a76b5959f9e25e1ac84c04d97c07db412f68783ef9d714b408e7",
    strip_prefix = "glog-e364e754a60af6f0eadd9902c4e76ecc060fee9c",
    urls = ["https://github.com/meteorcloudy/glog/archive/e364e754a60af6f0eadd9902c4e76ecc060fee9c.tar.gz"],
)

# Use a fork version of gflags with git_repository.
git_repository(
    name = "com_github_gflags_gflags",
    commit = "95995169e86f3fedd19696df5b1811d441c462a2",
    remote = "https://github.com/meteorcloudy/gflags.git",
)

# Use a patched version of bazel_skylib
http_archive(
    name = "bazel_skylib",
    patch_args = ["-p1"],
    patches = ["//:bazel_skylib.patch"],
    sha256 = "af87959afe497dc8dfd4c6cb66e1279cb98ccc84284619ebfec27d9c09a903de",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.0/bazel-skylib-1.2.0.tar.gz"],
)

# Depend on lib_a at a local path.
local_repository(
    name = "lib_a",
    path = "./lib_a",
)
