load("//:deps.bzl", "world_cities")
world_cities()

# Depend on lib_a at a local path.
local_repository(
    name = "lib_a",
    path = "./lib_a",
)

# This has to be defined after defining lib_a.
load("@lib_a//:deps.bzl", "emojis")
emojis()
