# Starlark codelab small logo reader components.

# TODO: Load get_logo_file_via_macro from logocommon/logocommon.bzl.

# TODO: Use get_logo_file_via_macro to build the small logo fiile.

java_binary(
    name = "logo_reader_small",
    srcs = ["LogoReaderSmall.java"],
    main_class = "exercise2.logoreadersmall.LogoReaderSmall",
    # TODO: Uncomment the following line when the TODOs above are resolved
    # resources = [":logo_small"],
)
