# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: TICS Action Setup
        uses: actions/checkout@v2
        with:
          repository: tiobetestlab/.github
          path: ./.github
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Download TICS wrappers
        uses: carlosperate/download-file-action@v1.0.3
        id: download-poetry
        with:
          file-url: 'https://tics.tiobe.com/download/buildserver.zip'
          file-name: 'buildserver.zip'
          location: './tics'
              
      - name: Extract TICS wrappers
        run: 7z x ./tics/buildserver.zip -o"$PWD/tics"
      
      - name: Add TICS to path
        run: echo "${{github.workspace}}/tics/BuildServer/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: TICS Action Run
        uses: ./.github/actions/tics
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TICS: https://testlab.tiobe.com/tiobeweb/testlab/api/cfg?name=testlab
        with:
          projectName: 'BazelCpp'
          branchName: 'master'
          ticsViewerUrl: 'https://testlab.tiobe.com/tiobeweb/testlab/'
          ticsAuthToken: 'NGUyOTFkMzMtM2ExYS00MDhjLTgzMDktMTVlNjBlYjZmMzM5OnBTWiVNUl5FZmdSLTpwQg'
          clientToken: 'bazel'
          tmpDir: 'C:/temp/bazel'
          calc: 'CW'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: TICSLog
          # A file, directory or wildcard pattern that describes what to upload
          path: C:/temp/bazel/ticstmpdir/tics.log
          # The desired behavior if no files are found using the provided path.
