# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: TICS Action Setup
        uses: actions/checkout@v2
        with:
          repository: tiobetestlab/.github
          path: ./.github
      
      - name: Download a file
        uses: carlosperate/download-file-action@v1.0.3
        id: download-poetry
        with:
          file-url: 'https://tics.tiobe.com/download/buildserver.zip'
          file-name: 'buildserver.zip'
          location: './tics/buildserver.zip'
          
      - name: Print the file path
        run: echo "The file was downloaded to ${{ steps.download-poetry.outputs.file-path }}" 
      
      - name: TICS Action Run
        uses: ./.github/actions/tics
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          projectName: 'BazelCpp'
          branchName: 'master'
          ticsViewerUrl: 'https://testlab.tiobe.com/tiobeweb/testlab/'
          ticsAuthToken: 'NGUyOTFkMzMtM2ExYS00MDhjLTgzMDktMTVlNjBlYjZmMzM5OnBTWiVNUl5FZmdSLTpwQg'
          clientToken: 'bazel'
          tmpDir: 'C:/temp/bazel'
          calc: 'CS,CW'
