
# Requires ANDROID_HOME set to the path of your Android SDK.
android_sdk_repository(
  name = "androidsdk",
)


GMAVEN_TAG = "20180530-1"
http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://github.com/bazelbuild/gmaven_rules/archive/%s.tar.gz" % GMAVEN_TAG,
)
load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")
gmaven_rules()


# Required for GenerateFirebaseXml tool.
maven_jar(
  name = "com_google_code_gson",
  artifact = "com.google.code.gson:gson:2.8.2",
)
